---
- hosts: all
  gather_facts: no
  tasks:
  
  - block:
    - name: Wait for instances to be reachable
      wait_for_connection:
        sleep: 5
        timeout: 600

  - block:
    - name: Gather Facts
      setup:

  - block:
    - name: Register with Subscription Manager
      redhat_subscription:
        state: present
        activationkey: "{{ secrets.activationkey }}"
        org_id: "{{ secrets.org_id }}"

    - name: Install insights-client
      package:
        name: insights-client
        state: present
      become: yes

    - name: Register with Red Hat Insights
      command: insights-client --register
      become: yes