---
- hosts: all
  become: True
  tasks:

  - name: "Install httpd"
    package:
      name: httpd
      state: present

  - name: "Start httpd service"
    service:
      name: httpd
      state: started
      enabled: yes