---
- hosts: all
  gather_facts: False

  vars:
    subnet: subnet-242cc86e
    sec_group:  sg-0a21a3ef9bf4884c0

  tasks:
    - name: Get Secrets
      block:
      - name: Get Activation Key
        include_vars: "secret.yml"

    - name: Provisioning EC2 instances
      block:

      - name: Provision instance(s)
        ec2:
          key_name: "{{ key_name }}"
          group_id: "{{ sec_group }}"
          image: "{{ image }}"
          instance_type: t2.micro
          region: "{{ region }}"
          vpc_subnet_id: "{{ subnet }}"
          wait: true
          assign_public_ip: yes
          count: 1
          instance_tags:
            Name: "{{ name }}"
            Owner: "Matt Hargrave"
            ansible: 1
            app: webdemo
        register: ec2

      - name: Set data
        set_stats:
          data:
            ec2: '{{ ec2 }}'
            activationkey: '{{ activationkey }}'
            org-id: '{{ org-id }}'